// classifier.js — decides whether a LinkedIn comment is low-effort / generic /
// likely AI-generated or automated spam. Two free, fully-local backends:
//   1. "builtin"  -> Chrome on-device Gemini Nano via the Prompt API (default)
//   2. "heuristic"-> pure regex/keyword scoring (always available, zero cost);
//                    also used as a pre-filter and as the fallback when the
//                    on-device model is unavailable.
//
// Nothing ever leaves the machine. All callers return a normalized verdict:
//   { spam: boolean, confidence: number (0..1), reason: string, source: string }
//
// This module is imported by the background service worker (an ES module).

// ---------------------------------------------------------------------------
// Shared prompt used by both LLM backends.
// ---------------------------------------------------------------------------
const SYSTEM_PROMPT = [
  "You are a strict but fair moderator for the comments on a person's own LinkedIn posts.",
  "Your job: decide whether a single comment is LOW-VALUE SPAM — meaning it is generic,",
  "low-effort, engagement-bait, promotional, or reads like it was auto-generated by a bot",
  "or AI with no real understanding of the post.",
  "",
  "Mark spam = true when the comment is things like: empty praise ('Great post!', 'So true',",
  "'Thanks for sharing', 'Well said'), vague AI filler, emoji-only, hashtag stuffing, a sales",
  "pitch ('DM me', 'check my profile', 'I help founders...'), or generic engagement bait",
  "('Thoughts?', 'Agree?') that adds nothing specific.",
  "",
  "Mark spam = false when the comment shows genuine human engagement: it references something",
  "specific from the post, shares a real opinion or experience, asks a substantive question,",
  "disagrees thoughtfully, or adds concrete information — even if short.",
  "",
  "Be CONSERVATIVE: if you are unsure, return spam = false. It is worse to delete a real",
  "comment than to leave one borderline comment up.",
  "",
  'Respond with ONLY a JSON object: {"spam": boolean, "confidence": number between 0 and 1, "reason": "short explanation"}',
].join("\n");

function buildUserPrompt({ author, text }) {
  return [
    `Commenter name: ${author || "(unknown)"}`,
    `Comment text:`,
    `"""`,
    (text || "").slice(0, 1500),
    `"""`,
    "",
    "Classify this comment. Respond with only the JSON object.",
  ].join("\n");
}

// JSON schema for structured output (used by both backends when supported).
const RESPONSE_SCHEMA = {
  type: "object",
  required: ["spam", "confidence", "reason"],
  additionalProperties: false,
  properties: {
    spam: { type: "boolean" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    reason: { type: "string" },
  },
};

// Defensive JSON extraction — pull the first {...} block out of a model reply.
function parseVerdict(raw, source) {
  if (!raw) return null;
  let text = String(raw).trim();
  // Strip code fences if the model wrapped the JSON.
  text = text.replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim();
  let obj;
  try {
    obj = JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) return null;
    try {
      obj = JSON.parse(match[0]);
    } catch {
      return null;
    }
  }
  if (typeof obj.spam !== "boolean") return null;
  let confidence = Number(obj.confidence);
  if (!Number.isFinite(confidence)) confidence = obj.spam ? 0.7 : 0.3;
  confidence = Math.max(0, Math.min(1, confidence));
  return {
    spam: obj.spam,
    confidence,
    reason: String(obj.reason || "").slice(0, 300),
    source,
  };
}

// ---------------------------------------------------------------------------
// 1) Heuristic backend — no model, no network. Also used as a pre-filter.
// ---------------------------------------------------------------------------
const GENERIC_PRAISE = [
  "great post", "great content", "great insights", "great point", "great share",
  "well said", "well put", "well articulated", "couldn't agree more", "could not agree more",
  "totally agree", "completely agree", "so true", "spot on", "this is gold", "love this",
  "thanks for sharing", "thank you for sharing", "thanks for posting", "needed this",
  "very insightful", "so insightful", "very informative", "valuable insights", "valuable content",
  "amazing post", "fantastic post", "awesome post", "powerful message", "important message",
  "100%", "facts", "this!", "well done", "nailed it", "absolutely", "preach", "underrated",
];

const AI_FILLER = [
  "in today's fast-paced world", "in today's digital age", "in the ever-evolving",
  "ever-evolving landscape", "navigate the complexities", "navigating the complexities",
  "it's important to note", "it is important to note", "it's worth noting", "at the end of the day",
  "game-changer", "game changer", "in the realm of", "a testament to", "underscores the importance",
  "harness the power", "unlock the potential", "delve into", "delving into", "let's delve",
  "moving forward", "leverage synergies", "drive synergy", "paradigm shift", "in conclusion",
  "circle back", "low-hanging fruit", "move the needle", "boils down to", "cannot be overstated",
];

const PROMOTIONAL = [
  "dm me", "dm for", "message me", "check my profile", "visit my profile", "link in bio",
  "check out my", "follow me", "book a call", "free guide", "free ebook", "free webinar",
  "i help", "we help", "join my", "sign up", "limited spots", "comment below and i'll",
  "comment 'yes'", "comment yes", "send me a dm", "click the link", "🔗", "join the waitlist",
];

const ENGAGEMENT_BAIT = [
  "thoughts?", "what do you think?", "agree?", "do you agree?", "who else", "am i right",
  "right?", "anyone else", "what's your take", "drop a", "tag someone",
];

function countEmoji(str) {
  // Rough emoji match across common ranges.
  const m = str.match(
    /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\u{FE0F}\u{1F1E6}-\u{1F1FF}]/gu
  );
  return m ? m.length : 0;
}

function countMatches(haystack, phrases) {
  let n = 0;
  const hits = [];
  for (const p of phrases) {
    if (haystack.includes(p)) {
      n++;
      hits.push(p);
    }
  }
  return { n, hits };
}

export function heuristicScore({ text }) {
  const raw = (text || "").trim();
  const lower = raw.toLowerCase();
  const reasons = [];
  let score = 0;

  if (!raw) {
    return { spam: false, confidence: 0, reason: "empty", source: "heuristic" };
  }

  const words = lower.split(/\s+/).filter(Boolean);
  const wordCount = words.length;
  const emojis = countEmoji(raw);
  const letters = (raw.match(/[a-z]/gi) || []).length;

  // Emoji-only or near emoji-only.
  if (emojis > 0 && letters <= 2) {
    score += 0.6;
    reasons.push("emoji-only");
  } else if (emojis >= 4) {
    score += 0.25;
    reasons.push("emoji-heavy");
  }

  const praise = countMatches(lower, GENERIC_PRAISE);
  if (praise.n) {
    score += 0.4 + (praise.n >= 2 ? 0.2 : 0);
    reasons.push(`generic praise: ${praise.hits.slice(0, 2).join(", ")}`);
  }

  const filler = countMatches(lower, AI_FILLER);
  if (filler.n) {
    score += 0.5 + (filler.n >= 2 ? 0.15 : 0);
    reasons.push(`ai filler: ${filler.hits.slice(0, 2).join(", ")}`);
  }

  const promo = countMatches(lower, PROMOTIONAL);
  if (promo.n) {
    score += 0.5;
    reasons.push(`promotional: ${promo.hits.slice(0, 2).join(", ")}`);
  }

  const bait = countMatches(lower, ENGAGEMENT_BAIT);
  if (bait.n && wordCount <= 8) {
    score += 0.35;
    reasons.push("engagement bait");
  }

  // Short comment dominated by generic/filler/promo/emoji is almost always spam.
  // (A long, substantive comment that merely contains a stock phrase is not.)
  if (wordCount > 0 && wordCount <= 6 && (praise.n || filler.n || promo.n || emojis >= 2)) {
    score += 0.2;
    reasons.push("short & generic");
  }

  // Explicit AI tells.
  if (/\bas an ai\b|\blanguage model\b|\bi'?m just an ai\b/.test(lower)) {
    score = Math.max(score, 0.9);
    reasons.push("explicit AI tell");
  }

  // Dampener: long, substantive comments with no spam signals are likely genuine.
  if (raw.length > 220 && praise.n === 0 && filler.n === 0 && promo.n === 0) {
    score = Math.max(0, score - 0.3);
  }

  score = Math.max(0, Math.min(1, score));
  return {
    spam: score >= 0.5,
    confidence: score,
    reason: reasons.length ? reasons.join("; ") : "no spam signals",
    source: "heuristic",
  };
}

// ---------------------------------------------------------------------------
// 2) Chrome built-in AI (Gemini Nano) via the Prompt API.
// ---------------------------------------------------------------------------
let _builtinSession = null;

export async function builtinAvailability() {
  try {
    if (typeof LanguageModel === "undefined") return "unsupported";
    // Newer API: LanguageModel.availability() -> 'unavailable'|'downloadable'|'downloading'|'available'
    if (typeof LanguageModel.availability === "function") {
      return await LanguageModel.availability();
    }
    // Older API surface.
    if (typeof LanguageModel.capabilities === "function") {
      const c = await LanguageModel.capabilities();
      return c?.available ?? "unsupported";
    }
    return "unsupported";
  } catch {
    return "unsupported";
  }
}

async function getBuiltinSession() {
  if (_builtinSession) return _builtinSession;
  if (typeof LanguageModel === "undefined") throw new Error("Built-in AI not available");
  _builtinSession = await LanguageModel.create({
    initialPrompts: [{ role: "system", content: SYSTEM_PROMPT }],
  });
  return _builtinSession;
}

export async function classifyWithBuiltin(comment) {
  let session;
  try {
    session = await getBuiltinSession();
  } catch (e) {
    return null;
  }
  const userPrompt = buildUserPrompt(comment);
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      let raw;
      try {
        // Preferred: constrained JSON output (recent Chrome).
        raw = await session.prompt(userPrompt, { responseConstraint: RESPONSE_SCHEMA });
      } catch {
        raw = await session.prompt(userPrompt);
      }
      const verdict = parseVerdict(raw, "builtin");
      if (verdict) return verdict;
      return null;
    } catch (e) {
      // Session may have been invalidated (worker recycled); recreate once.
      _builtinSession = null;
      try {
        session = await getBuiltinSession();
      } catch {
        return null;
      }
    }
  }
  return null;
}
